name: CI/CD for Flask App with Docker and EC2

on:
  push:
    branches: ["main"]

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/claco-ai-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/claco-ai-app:latest

  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
          set -e
          
          echo "Stopping container using port 5000..."
          existing_container_id=\$(docker ps --format "{{.ID}} {{.Ports}}" | grep "0.0.0.0:5000" | awk '{print \$1}')
          if [ -n "\$existing_container_id" ]; then
            echo "Found container using port 5000. Stopping it..."
            docker stop \$existing_container_id
            docker rm \$existing_container_id
          else
            echo "No container is using port 5000."
          fi
          
          echo "Pulling the latest Docker image..."
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker pull ${{ secrets.DOCKER_USERNAME }}/claco-ai-app:latest
          
          echo "Starting new container..."
          docker run -d --name claco-ai-app -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/claco-ai-app:latest
          EOF
