name: CI/CD for Flask App with Docker and EC2

on:
  push:
    branches: ["main"]

jobs:
  build-and-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          # Create a unique tag using Git SHA
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/claco-ai-app:${{ github.sha }}
          
          echo "Building Docker Image with tag $IMAGE_TAG..."
          docker build -t $IMAGE_TAG .
          
          echo "Pushing Docker Image to Docker Hub..."
          docker push $IMAGE_TAG
          
          # Save tag for deployment step
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

  deploy-to-ec2:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
          set -e
          
          echo "Pulling the latest Docker image..."
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker pull $IMAGE_TAG
          
          echo "Starting new container with unique name..."
          docker run -d --name claco-ai-app-${{ github.sha }} -p 5000:5000 $IMAGE_TAG
          EOF
